on:
    workflow_dispatch: 
  
name: Create RPM Release

jobs:
  buildsrpm:
    name: Build SRPM
    runs-on: ubuntu-latest
    container: 
      image: fedora:41
      options: --cap-add=SYS_ADMIN
    steps:
      - name: Build SRPM 
        shell: bash
        id: rpm_build
        run: |
          dnf copr enable secureblue/trivalent -y
          dnf update -y
          dnf install git mock wget rpmbuild trivalent-chromium-clean-source -y
          git clone https://github.com/secureblue/Trivalent.git
          bash ./Trivalent/copr_script.sh
          rpmbuild -bs -v --define "_sourcedir $PWD" --define "_rpmdir $PWD" --define "_builddir $PWD" --define "_specdir $PWD" --define "_srcrpmdir $PWD" trivalent.spec
          

      - name: Save SRPM
        uses: actions/upload-artifact@v4
        with:
          name: srpm-artifact
          path: "*.rpm"
          retention-days: 1

  buildrpm:
    name: Build RPM
    runs-on: ubuntu-latest
    needs: buildsrpm
    steps:      
      - name: Retrieve SRPM
        uses: actions/download-artifact@v4
        with:
          name: srpm-artifact
          path: "*.rpm"
      - name: Build RPM 
        shell: bash
        id: rpm_build
        run: |
          sudo apt-get install rpmbuild mock
          rpmbuild -bs -v --define "_sourcedir $PWD" --define "_rpmdir $PWD" --define "_builddir $PWD" --define "_specdir $PWD" --define "_srcrpmdir $PWD" trivalent.spec
          mock --resultdir=dist -r fedora-41-x86_64 --rebuild trivalent-*.src.rpm
          mkdir ${{ github.workspace }}/RPMOutput
          cp *.rpm "${{ github.workspace }}/RPMOutput

      - name: Save RPM
        uses: actions/upload-artifact@v4
        with:
          name: rpm-artifact
          path: "*.rpm"
          retention-days: 1